#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:4444/javauniversity
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#      database: postgresql
#      database-platform: org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.url=jdbc:postgresql://localhost:4444/javauniversity
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.mvc.hiddenmethod.filter.enabled=true